# Generated by Django 5.2.7 on 2026-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_id_alter_rewardpoint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pending_staff_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
    ]
